### ISSUE TITLE
[Bug]: presets aren't showing up on fedora

### ISSUE THREAD

**Issue by koruninn** [luisbocanegra/plasma-panel-colorizer#113]
i tried to install the plugin from the kde store and manually but there's no way i can see the presets whatsoever and i also checked the dependencies were installed and the presets were placed in the right folder

![Captura de pantalla_20241101_150504](https://github.com/user-attachments/assets/32240e79-c7fc-4ca1-8fd4-d932abf5717d)

**Desktop (please complete the following information):**
 - Operating System: fedora 41
 - KDE Plasma Version: 6.2.2
 - KDE Frameworks Version: 6.7.0
 - Qt Version: 6.8.0
 - Graphics Platform: wayland

**Comment by luisbocanegra** [comment]
Hi @koruninn

Which version of the widget are you using? [There was a bug listing presets in some distros](https://github.com/luisbocanegra/plasma-panel-colorizer/issues/99) and was fixed in [v1.0.1](https://github.com/luisbocanegra/plasma-panel-colorizer/releases/tag/v1.0.1).

If you're running an older version updating and restarting Plasma or logging out should fix the issue.
If you're already using the latest version but the bug is still there please do the try the last commit:

```
git clone https://github.com/luisbocanegra/plasma-panel-colorizer
cd plasma-panel-colorizer
kpackagetool6 -t Plasma/Applet -u package/
```

Then run `cournalctl -f` before opening the presets tab and paste what you get after the presets page loads

**Comment by koruninn** [comment]
thank you so much! updating to the latest commit did solve the issue

here's the output of `journalctl -f` in case it's still neccesary

nov 01 18:09:15 fedora systemd[1484]: Finished grub-boot-success.service - Mark boot as successful.
nov 01 18:09:19 fedora systemd[1484]: Started app-org.kde.dolphin@826635894cba40359e959829bb353ab3.service - Dolphin - Gestor de archivos.
nov 01 18:09:20 fedora systemd[1]: Starting sssd-kcm.service - SSSD Kerberos Cache Manager...
nov 01 18:09:20 fedora systemd[1]: Started sssd-kcm.service - SSSD Kerberos Cache Manager.
nov 01 18:09:20 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=sssd-kcm comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
nov 01 18:09:20 fedora sssd_kcm[5038]: Starting up
nov 01 18:09:52 fedora plasmashell[2046]: KPackageStructure of KPluginMetaData(pluginId:"Minimal.chaac.weather", fileName: "/home/koru/.local/share/plasma/plasmoids/Minimal.chaac.weather/metadata.json") does not match requested format "Plasma/Applet"
nov 01 18:09:52 fedora plasmashell[2046]: KPackageStructure of KPluginMetaData(pluginId:"Minimal.chaac.weather", fileName: "/home/koru/.local/share/plasma/plasmoids/Minimal.chaac.weather/metadata.json") does not match requested format "Plasma/Applet"
nov 01 18:09:52 fedora plasmashell[2046]: KPackageStructure of KPluginMetaData(pluginId:"Minimal.chaac.weather", fileName: "/home/koru/.local/share/plasma/plasmoids/Minimal.chaac.weather/metadata.json") does not match requested format "Plasma/Applet"
nov 01 18:10:13 fedora PackageKit[2603]: search-file transaction /268_dbbadebd from uid 1000 finished with success after 513ms
nov 01 18:10:37 fedora konsole[4761]: kf.windowsystem: static int KX11Extras::currentDesktop() may only be used on X11
nov 01 18:10:37 fedora konsole[4761]: kf.windowsystem: static void KX11Extras::setOnDesktop(WId, int) may only be used on X11
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:14:1: QML SimpleKCM: Created graphical object was not placed in the graphics scene.
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_configurationOverrides
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_configurationOverridesDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_enableDebug
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_enableDebugDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_forceForegroundColor
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_forceForegroundColorDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_globalSettingsDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_hideWidget
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_hideWidgetDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_isEnabledDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_lastPresetDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_panelWidgets
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_panelWidgetsDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_presetAutoloading
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml: Setting initial properties failed: SimpleKCM does not have a property called cfg_presetAutoloadingDefault
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:109:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:109:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:109:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:109:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:99:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:99:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:99:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:99:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:88:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:88:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:88:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:88:5: QML PromptDialog: Binding loop detected for property "implicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:279:5
nov 01 18:11:02 fedora plasmashell[2046]: qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344:18: QML ScrollView: Binding loop detected for property "calculatedImplicitHeight":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:361:9
nov 01 18:11:02 fedora plasmashell[2046]: qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401:33: QML Binding: Binding loop detected for property "value":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:409:13
nov 01 18:11:02 fedora plasmashell[2046]: qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344:18: QML ScrollView: Binding loop detected for property "calculatedImplicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:358:9
nov 01 18:11:02 fedora plasmashell[2046]: qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344:18: QML ScrollView: Binding loop detected for property "calculatedImplicitHeight":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:361:9
nov 01 18:11:02 fedora plasmashell[2046]: qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401:33: QML Binding: Binding loop detected for property "value":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:409:13
nov 01 18:11:02 fedora plasmashell[2046]: qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344:18: QML ScrollView: Binding loop detected for property "calculatedImplicitWidth":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:358:9
nov 01 18:11:02 fedora plasmashell[2046]: qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:344:18: QML ScrollView: Binding loop detected for property "calculatedImplicitHeight":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:361:9
nov 01 18:11:02 fedora plasmashell[2046]: qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:401:33: QML Binding: Binding loop detected for property "value":
                                          qrc:/qt/qml/org/kde/kirigami/dialogs/Dialog.qml:409:13
nov 01 18:11:02 fedora plasmashell[2046]: file:///home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/configPresets.qml:34:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
nov 01 18:11:02 fedora plasmashell[2046]: qml: mkdir -p '/home/koru/.config/panel-colorizer/presets/' 0 0
nov 01 18:11:02 fedora plasmashell[2046]: qml: '/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/tools/list_presets.sh' '/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/' b;'/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/tools/list_presets.sh' '/home/koru/.config/panel-colorizer/presets/' 0 0 b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Blur Widgets
                                          b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/ChromeOS
                                          b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Fake Floating
                                          b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Neon Lights
                                          b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Rounded Widgets
                                          b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Rounded Widgets Floating
                                          b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Skeuomorphic white
                                          b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Solid
                                          b:/home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Transparent
                                          u:/home/koru/.config/panel-colorizer/presets/Blur Widgets
                                          u:/home/koru/.config/panel-colorizer/presets/ChromeOS
                                          u:/home/koru/.config/panel-colorizer/presets/Fake Floating
                                          u:/home/koru/.config/panel-colorizer/presets/Neon Lights
                                          u:/home/koru/.config/panel-colorizer/presets/Rounded Widgets
                                          u:/home/koru/.config/panel-colorizer/presets/Rounded Widgets Floating
                                          u:/home/koru/.config/panel-colorizer/presets/Skeuomorphic white
                                          u:/home/koru/.config/panel-colorizer/presets/Solid
                                          u:/home/koru/.config/panel-colorizer/presets/Transparent
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Blur Widgets
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/ChromeOS
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Fake Floating
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Neon Lights
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Rounded Widgets
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Rounded Widgets Floating
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Skeuomorphic white
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Solid
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.local/share/plasma/plasmoids/luisbocanegra.panel.colorizer/contents/ui/presets/Transparent
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/Blur Widgets
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/ChromeOS
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/Fake Floating
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/Neon Lights
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/Rounded Widgets
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/Rounded Widgets Floating
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/Skeuomorphic white
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/Solid
nov 01 18:11:02 fedora plasmashell[2046]: qml: /home/koru/.config/panel-colorizer/presets/Transparent

**Comment by luisbocanegra** [comment]
Thanks for the confirmation. If you install v1.0.1 does the bug come back?

I tried in a Fedora VM by installing from Get New Widgets thingy and it listed presets correctly, maybe you were running version 1.0.0 before updating to the last commit?

**Comment by koruninn** [comment]
it seems to be sorted out now, initially i installed it through the get new widgets menu but i agree it might have been version 1.0.0 and i suspected things should work if i followed the manual installation process and despite having updated to version 1.0.1 the issue persisted and thus i made this bug report. since i updated to the last commit i have no issues whatsoever

**Comment by luisbocanegra** [comment]
Can you quickly download and install https://github.com/luisbocanegra/plasma-panel-colorizer/releases/download/v1.0.1/plasmoid-panel-colorizer-v1.0.1.plasmoid by running `kpackagetool6 -t Plasma/Applet -u plasmoid-panel-colorizer-v1.0.0.plasmoid` and restarting plasmashell with `systemctl --user restart plasma-plasmashell` just make sure anything important is saved in case some program decides to close.

I just want to confirm if there is something I may have overlooked that could bring back the bug.

**Comment by luisbocanegra** [comment]
Also from the log you seem to have duplicate presets, if you haven't modified them you might want to delete them so they don't override future updates of their built-in counterparts.

**Comment by koruninn** [comment]
i'll set up a fedora virtual machine in a while and will try it out. as for the duplicate presets you're right, i found out not too long ago and got rid of them, thanks!

**Comment by koruninn** [comment]
i couldn't install it by running the command you mentioned but i hit the button in get new widgets that allowed me to install it manually and that worked. as for the plasmoid itself it seems to be working as expected, everything loads properly this time. hope this helps
![Captura de pantalla_20241101_233022](https://github.com/user-attachments/assets/852385e9-3011-4279-aeab-7772497328c6)

**Comment by luisbocanegra** [comment]
Most likely you were running v1.0.0 when you had the bug, will close this now.

Thanks again for the testing.
